/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StayRouteImport } from './routes/stay'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as IndexRouteImport } from './routes/index'

const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concierge': typeof ConciergeRoute
  '/services': typeof ServicesRoute
  '/stay': typeof StayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concierge': typeof ConciergeRoute
  '/services': typeof ServicesRoute
  '/stay': typeof StayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concierge': typeof ConciergeRoute
  '/services': typeof ServicesRoute
  '/stay': typeof StayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/concierge' | '/services' | '/stay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/concierge' | '/services' | '/stay'
  id: '__root__' | '/' | '/concierge' | '/services' | '/stay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConciergeRoute: typeof ConciergeRoute
  ServicesRoute: typeof ServicesRoute
  StayRoute: typeof StayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConciergeRoute: ConciergeRoute,
  ServicesRoute: ServicesRoute,
  StayRoute: StayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
